manifest/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        
    <fullName>Competitor_1_Price__c</fullName>
        
    <description>Created as part of Apex Academy with David Liu</description>
        
        
    <label>Competitor 1 Price</label>
        
    <precision>18</precision>
        
        
    <scale>0</scale>
        
        
        
    <type>Currency</type>
        
</fields>
    <fields>
        
    <fullName>Competitor_1__c</fullName>
        
    <description>Created as part of Apex Academy with David Liu</description>
        
        
    <label>Competitor 1</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Opportunity_Competitor</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>Competitor_2_Price__c</fullName>
        
    <description>Created as part of Apex Academy with David Liu</description>
        
        
    <label>Competitor 2 Price</label>
        
    <precision>18</precision>
        
        
    <scale>0</scale>
        
        
        
    <type>Currency</type>
        
</fields>
    <fields>
        
    <fullName>Competitor_2__c</fullName>
        
    <description>Created as part of Apex Academy with David Liu</description>
        
        
    <label>Competitor 2</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Opportunity_Competitor</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>Competitor_3_Price__c</fullName>
        
    <description>Created as part of Apex Academy with David Liu</description>
        
        
    <label>Competitor 3 Price</label>
        
    <precision>18</precision>
        
        
    <scale>0</scale>
        
        
        
    <type>Currency</type>
        
</fields>
    <fields>
        
    <fullName>Competitor_3__c</fullName>
        
    <description>Created as part of Apex Academy with David Liu</description>
        
        
    <label>Competitor 3</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Opportunity_Competitor</valueSetName>
            
    </valueSet>
        
</fields>
</CustomObject>

manifest/globalValueSets/Opportunity_Competitor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Microsoft</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo!</fullName>
    </customValue>
    <description>List of opportunity competitors. Created as part of Apex Academy with David Liu</description>
    <masterLabel>Opportunity Competitor</masterLabel>
</GlobalValueSet>

manifest/classes/LeadingCompetitorTest.cls
@isTest
private class LeadingCompetitorTest {
    @isTest
    static void createOpportunity() {
        // Create an opportunity and set required fields
        Opportunity opp = new Opportunity();
        opp.Name        = 'Apex Academy';
        opp.CloseDate   = Date.today();
        opp.StageName   = 'Prospecting';

        //Set competitor fields
        opp.Competitor_1__c = 'Amazon';
        opp.Competitor_2__c = 'Google';
        opp.Competitor_3__c = 'Salesforce';

        //Set competitor price fields
        opp.Competitor_1_Price__c = 10000;
        opp.Competitor_2_Price__c = 2000;
        opp.Competitor_3_Price__c = 1999;
        
        insert opp;
        System.debug('Opportunity '+ opp.Name + ' inserted with all competitor fields populated.');
    }
}